### ISSUE TITLE
Create plan for what the fuck to do.

### ISSUE THREAD

**Issue by Axemen** [Axemen/classification_comparison#2]
Create plan for development and what steps need to be complete for minimum coverage of basic goals.

On that note outline basic goals.

**Comment by joshua-montanari** [comment]
Just so we are clear, you would like me to create an outline of what were supposed to do?

**Comment by Axemen** [comment]
No this is just an issue that we both need to work on. I'm going to develop the plan for the backend and what information needs to be displayed on the front end and you're going to design the front end. @joshua-montanari

**Comment by Axemen** [comment]
# Goal

The goal is to create a simple system that will create a report that can be easily shared throughout a team with minimal effort and allow it to be run with minimal code on the python side. 

# THE PLAN

Use a local HTML file that will contain the JS in order to read the output of models in JSON form in a folder containing them to allow easy sharing of the report and easy comparison of the different models. 

### STEPS

1. Use python to compare the models and capture the output. 
2. Use python to save the output of the models to JSON files inside of a particular folder.
3. Use python to copy a pre-made HTML file that will contain the JS and read from the JSON files to display the models that have been run. 
4. Dynamically render the outputs of the models based on the JSON files. 
    * This also will render every model output that is currently in the folder containing the JSON files.

**Comment by Axemen** [comment]
# File Structure of Report

* Project Folder
    * running_models.ipynb
    * idk_what_im_doing.ipynb
    * report
         * report.html
         * model_one.json
         * model_two.json
         * model_three.json


It may be better to have them in one json file instead but the structure would be the same.
